BaSD-MS-19: Create clients react logic
BaSD-2021/Aquiles-MindSet-app pull request #1
Opened 2021-11-28 18:37 UTC by ignacioaristo

### Resume:
Frontend was connected with backend using React.

**Methods developed for Clients:**

- Get all the Clients

- Create a Client

> Click on Add Client button to display the form.

- Update a Client

> Click on the row of the Client to display the form and rewrite it.

- Delete a Client

> Click on the trash can icon to delete the Client.

Modal was created for delete option.

Validations were added to every form.

2021-12-02 03:17 UTC, aquilesmariani requested changes
We should consider keeping `package-lock.json` file as well, I don't know if you meant to delete it but we need to keep track of it in git

2021-12-02 03:17 UTC, aquilesmariani commented on src/Components/Clients/Form/FormClients.js
> +      return error;
It doesn't have much sense to just return the error, let's show it into the UI

2021-12-02 12:23 UTC, ignacioaristo commented on .eslintrc.json
> +  "extends": ["eslint:recommended", "plugin:react/recommended" /*, "plugin:prettier/recommended"*/],
Yes i did, now were removed.

2021-12-02 12:28 UTC, ignacioaristo commented on .eslintrc.json
> +    // "prettier/prettier": [
Fixed.

2021-12-02 12:38 UTC, ignacioaristo commented on src/Components/Clients/Form/FormClients.js
> +      fetch(`${process.env.REACT_APP_API}/api/clients/id/${clientId}`)
Fixed it.

2021-12-02 15:55 UTC, ignacioaristo commented on src/Components/Clients/Form/FormClients.js
> +              throw new Error(message);
Modal was added.

2021-12-02 15:55 UTC, ignacioaristo commented on src/Components/Clients/index.js
> +            throw new Error(message);
Modal was added.

2021-12-02 15:55 UTC, ignacioaristo commented on src/Components/Clients/Form/FormClients.js
> +      return error;
Modal was added.

2021-12-02 16:21 UTC, aquilesmariani requested changes
Almost there!

2021-12-02 16:21 UTC, aquilesmariani commented on src/Components/Clients/Form/FormClients.js
> +      window.location.href = `/clients`;
This is redirecting you at this moment, let's put this after the request when it's successful

2021-12-02 16:21 UTC, aquilesmariani commented on src/Components/Clients/Form/FormClients.js
> +      window.location.href = `/clients`;
Same as above

2021-12-02 16:21 UTC, aquilesmariani commented on src/Components/Clients/index.js
> +            return (
```suggestion
          {clients.map((client) => (
```

2021-12-02 16:21 UTC, aquilesmariani commented on src/Components/Clients/Modal/modalClient.module.css
> +  color: white;
Let's start putting colors with hex so we keep consistency across the CSS files

2021-12-02 19:37 UTC, ignacioaristo commented on src/Components/Clients/Modal/modalClient.module.css
> +  color: white;
Changed

2021-12-02 22:31 UTC, ignacioaristo commented on src/Components/Clients/Form/FormClients.js
> +      window.location.href = `/clients`;
Modal was created for error message

2021-12-02 22:31 UTC, ignacioaristo commented on src/Components/Clients/Form/FormClients.js
> +      window.location.href = `/clients`;
Fixex

2021-12-02 22:33 UTC, ignacioaristo commented on src/Components/Clients/index.js
> +            return (
Return removed

2021-12-03 00:52 UTC, aquilesmariani approved these changes
Looks great!

2021-12-03 01:50 UTC, merged