BaSD-MS-36: Block buttons on loading
BaSD-2021/Aquiles-MindSet-app pull request #11
Opened 2021-12-05 00:20 UTC by ignacioaristo

A component `IsLoading ` was created, it shows when the servers need to retrieve data and disappear when the call ends.

![image](https://user-images.githubusercontent.com/72083744/144728694-cb35b867-5f38-472f-a9d7-663d9f43cc97.png)

2021-12-05 17:04 UTC, leimeterjoaquin approved these changes

2021-12-07 12:59 UTC, aquilesmariani requested changes
Some tweaks to go.

2021-12-07 12:59 UTC, aquilesmariani commented on src/Components/Admins/Form/index.js
> +
I don't think curly braces are needed for this case
```suggestion
  if (isLoading) return <IsLoading />;
```

2021-12-07 12:59 UTC, aquilesmariani commented on src/Components/Admins/index.js
> +
Same as above

2021-12-07 12:59 UTC, aquilesmariani commented on src/Components/Applications/index.js
> +      .catch((error) => error)
Can you show the error in the modal? Seems like this got merged into development without a fix

2021-12-07 15:12 UTC, leimeterjoaquin commented on src/Components/Applications/index.js
> +      .catch((error) => error)
All this issues are fixed in MS-34: Modal

2021-12-08 12:06 UTC, aquilesmariani approved these changes
👌

2021-12-08 12:30 UTC, merged