BaSD-MS-20: create crud for interviews
BaSD-2021/Aquiles-MindSet-app pull request #12
Opened 2021-12-05 14:35 UTC by rodrisibrins

2021-12-05 17:48 UTC, leimeterjoaquin requested changes

2021-12-05 17:48 UTC, leimeterjoaquin commented on src/Components/Interviews/Form/FormInterviews.js
> +        <input
You could have an actual placeholder text that passes the validations, like 1998/05/19 for date, because I can't know what format to write the date in. Or have an input type:"date"

2021-12-05 17:48 UTC, leimeterjoaquin commented on src/Components/Interviews/index.js
> +              <td>{interview.date}</td>
here you could cut the string to not have the whole T00:00:00.000Z.
something like
```
<td>{interview.date.substring(0, 10)} </td>
```
would work just fine I think

2021-12-05 17:48 UTC, leimeterjoaquin commented on src/Components/Interviews/Form/FormInterviews.js
> +      fetch(`${process.env.REACT_APP_API}/interviews/id/${InterviewId}`)
When I click on an interview the fetch fails, showing this error
![image](https://user-images.githubusercontent.com/53354878/144757380-d633db94-9462-41eb-9d5a-fbb87d1e9550.png)
I am almost sure the problem is in this line, you need to erase the "id/"
leave it like:
```
fetch(`${process.env.REACT_APP_API}/interviews/${InterviewId}`)
```
But maybe i'm wrong, I do know that the fetch is failing.
I just saw in the server that the route to get an interview is the following
```
interviewsRouter.get('/interview/:id', getInterviewsById);
```
So if you change this line i'll probably work

2021-12-07 13:06 UTC, aquilesmariani requested changes
I also have this modal when I successfully delete an interview.

![image](https://user-images.githubusercontent.com/8579539/145034580-61c0a1e9-b876-4ca1-b545-e0635b6a89db.png)

2021-12-07 13:06 UTC, aquilesmariani commented on src/Components/Interviews/Form/FormInterviews.js
> +  const InterviewId = params.get('id');
```suggestion
  const interviewId = params.get('id');
```

2021-12-07 13:06 UTC, aquilesmariani commented on src/Components/Interviews/Form/form.module.css
> +input {
Try not to use element selectors, this could affect on the entire app

2021-12-07 15:15 UTC, leimeterjoaquin commented on src/Components/Interviews/Form/form.module.css
> +input {
You should write 
```
.container > * input {
...
}
```
to refer to all inputs in the file.

2021-12-10 16:37 UTC, leimeterjoaquin approved these changes

2021-12-17 00:57 UTC, aquilesmariani approved these changes
Looks 👍

2021-12-17 12:12 UTC, merged