Input
BaSD-2021/Aquiles-MindSet-app pull request #13
Opened 2021-12-06 12:54 UTC by MicaQuarleri

Shared input was created and added to every entity.

2021-12-06 17:22 UTC, leimeterjoaquin approved these changes
Great!

2021-12-07 13:32 UTC, aquilesmariani requested changes
I think we should rename the form component filenames so they are just `index.js` since we are already providing the entity name and the Form type of component in the path (e.g `/Components/Interviews/Form`)
Please refer to the message I left on slack for more info.

2021-12-07 13:32 UTC, aquilesmariani commented on src/Components/Councelors/Form/FormCounselor.js
> +          console.log(response);
Please remove this console.log

2021-12-07 13:32 UTC, aquilesmariani commented on src/Components/Councelors/Form/FormCounselor.js
> +      console.log(phoneValue);
Remove this one as well

2021-12-11 16:00 UTC, aquilesmariani approved these changes
Looks nice!

2021-12-11 16:32 UTC, merged