BaSD-MS-34: Modal
BaSD-2021/Aquiles-MindSet-app pull request #14
Opened 2021-12-06 20:39 UTC by leimeterjoaquin

# Modal
## 2 componentes created:
-Modal
-ErrorModal
## notes
implemented on all entitites exept for profiles and interviews
## image
![image](https://user-images.githubusercontent.com/53354878/144918951-5827d386-51e4-450d-a692-bcca8275b9c1.png)

2021-12-06 23:36 UTC, MicaQuarleri requested changes
In the delete of applications, when you when you click delete in the modal button it is deleted from the database but the modal does not disappear

2021-12-07 01:07 UTC, MicaQuarleri approved these changes

2021-12-07 13:42 UTC, aquilesmariani requested changes
Looks pretty good!

I think we should rename the form component filenames so they are just index.js since we are already providing the entity name and the Form type of component in the path (e.g /Components/Interviews/Form)

Please refer to the message I left on slack for more info.

2021-12-07 13:42 UTC, aquilesmariani commented on src/Components/Admins/Form/index.js
> +            span: 'are you sure you want to save these changes?'
I'd rather starting messages with a capital letter
```suggestion
            span: 'Are you sure you want to save these changes?'
```

2021-12-07 13:42 UTC, aquilesmariani commented on src/Components/Shared/Modal/index.jsx
> +  //TODO: change styles after reset
Just a question, is this still needed?

2021-12-07 13:42 UTC, aquilesmariani commented on src/Components/Shared/Modal/index.jsx
> +          <button onClick={() => actionEntity()}>{leftButtonText.toUpperCase()}</button>
If you don't have to send values through params you can just do this
```suggestion
          <button onClick={actionEntity}>{leftButtonText.toUpperCase()}</button>
```

2021-12-07 15:06 UTC, leimeterjoaquin commented on src/Components/Shared/Modal/index.jsx
> +  //TODO: change styles after reset
Yes I should erase that. Maybe add those changes through a new branch later on.

2021-12-07 15:23 UTC, aquilesmariani approved these changes

2021-12-08 15:21 UTC, merged