Tech leader
BaSD-2021/Aquiles-MindSet-app pull request #15
Opened 2021-12-06 22:33 UTC by ManuelLopezAnido

Routes done ✓
Navbar component done ✓
Layout component done ✓

2021-12-06 23:18 UTC, leimeterjoaquin approved these changes

2021-12-06 23:22 UTC, MicaQuarleri approved these changes

2021-12-06 23:49 UTC, aquilesmariani requested changes
Just a few comments to go

2021-12-06 23:49 UTC, aquilesmariani commented on src/Components/Postulants/Form/index.js
>        .then((response) => response.json())
If you're not using the response,  I think it's better not to parse the result and just redirect the page will be fine

2021-12-06 23:49 UTC, aquilesmariani commented on src/Components/Positions/Form/index.js
> +  const PosId = params.get('id');
```suggestion
  const posId = params.get('id');
```

2021-12-06 23:49 UTC, aquilesmariani commented on src/Components/Positions/Form/index.js
> +        return response.json();
Let's redirect here instead of using a new `.then`

2021-12-06 23:49 UTC, aquilesmariani commented on src/Components/Header/index.js
> +  let Entity = location.pathname;
```suggestion
  let entity = location.pathname;
```

2021-12-07 02:10 UTC, aquilesmariani approved these changes

2021-12-07 17:11 UTC, merged