Feature/ms 44/applications redux
BaSD-2021/Aquiles-MindSet-app pull request #19
Opened 2021-12-14 01:54 UTC by ManuelLopezAnido

Implementar el modelo "Admin" en redux y definir:
Llamados asincrónicos teniendo en cuenta el estado Fetching, Fullfiled y Rejected. Crear la estructura de carptetas del modulo teniendo en cuenta: constants, actions, reducer, thunks. ✓

Generar la implementacion de redux con react para la definición de todos los llamados asincrónicos y reemplazar la lógica utilizada actualmente en los componentes. ✓

2021-12-15 14:27 UTC, leimeterjoaquin requested changes

2021-12-15 14:27 UTC, leimeterjoaquin commented on src/Components/Shared/ErrorModal/index.jsx
> +          <span>{showModal}</span>
Remember that if we change something in shared components, we must make changes on every component that's using it. Let's discuss with the team if this is an improvement or if we should keep it the way it is right now

2021-12-15 14:27 UTC, leimeterjoaquin commented on src/redux/applications/actions.js
> +export const errorToDefault = () => ({
You set this action but never use it.

2021-12-15 14:27 UTC, leimeterjoaquin commented on src/redux/applications/reducer.js
> +    case ERROR_TO_DEFAULT: {
Same here. This case is never used.

2021-12-15 14:36 UTC, leimeterjoaquin commented
Please name the branch BaSD-MS-44: applications redux

2021-12-19 22:30 UTC, leimeterjoaquin approved these changes

2021-12-19 22:33 UTC, aquilesmariani approved these changes
Please don't forget to remove `console.log` before making any commit.

Still want to review `NoData` component, but let's get this merged ASAP

2021-12-19 23:16 UTC, merged