BaSD/MS-47/Counselors: added the logic of redux
BaSD-2021/Aquiles-MindSet-app pull request #20
Opened 2021-12-14 02:12 UTC by MicaQuarleri

### **Important**:
First merge de server PR #36

2021-12-15 14:48 UTC, leimeterjoaquin requested changes
Rename PR to:
`BasD-MS-47: Counselors redux`

2021-12-15 14:48 UTC, leimeterjoaquin commented on src/Components/Layout/layout.module.css
> +  min-height: 160vh;
I think this affects everyone. if the minimum height is 160vh the layout is going to be bigger on every page. Also in the heroku deploy I see the old buttons. Did you pull development?

2021-12-15 14:48 UTC, leimeterjoaquin commented on src/index.js
> +import { composeWithDevTools } from 'redux-devtools-extension';
This is already done in development.
- stand on your branch
- git fetch
- git merge origin/development
- resolve conflicts
- git add .
- git commit
- write :wq to exit the commit

2021-12-17 03:01 UTC, aquilesmariani requested changes

2021-12-17 14:00 UTC, aquilesmariani requested changes

2021-12-17 14:00 UTC, aquilesmariani commented on src/Components/Layout/layout.module.css
> +  min-height: 160vh;
@MicaQuarleri remember to remove this `min-height` property

2021-12-17 23:23 UTC, aquilesmariani approved these changes
Looks great!

2021-12-18 00:33 UTC, leimeterjoaquin approved these changes

2021-12-18 00:45 UTC, merged