MS-51: Changes to feature position
BaSD-2021/Aquiles-MindSet-app pull request #21
Opened 2021-12-14 02:16 UTC by ManuelLopezAnido

Implementar el modelo "Admin" en redux y definir:
Llamados asincrónicos teniendo en cuenta el estado Fetching, Fullfiled y Rejected. Crear la estructura de carptetas del modulo teniendo en cuenta: constants, actions, reducer, thunks. ✔ 

Generar la implementacion de redux con react para la definición de todos los llamados asincrónicos y reemplazar la lógica utilizada actualmente en los componentes. ✔

2021-12-15 15:03 UTC, leimeterjoaquin requested changes
Everything else looks great. Just the modal thing

2021-12-15 15:03 UTC, leimeterjoaquin commented on src/Components/Shared/ErrorModal/index.jsx
> -const ErrorModal = ({ showModal, titleText, closeModal, middleText, buttonText }) => {
The same as in MS-44. This change is not bad or anything, but should be discussed with the team. 
This is to not have the error and errorMessage in the store. Makes sense but this could have been said when MS-43: Tech Leader was up for review.

2021-12-17 04:13 UTC, aquilesmariani requested changes
1.  Please also fix this issue by adding height and overflow-y props in the form container class  <img width="603" alt="Screen Shot 2021-12-17 at 00 35 35" src="https://user-images.githubusercontent.com/8579539/146487771-65bff880-5a0c-4832-87ab-749101e666fb.png">

2. Dates should be parsed in order to get inputs working 

Consider using `replaceAll('/', '-')` or `new Date(datePosted || 0).toISOString().split('T')[0]` inside of the value prop of each date input to format the date before rendering it.
Otherwise you will never see saved data into the field.

2021-12-17 04:13 UTC, aquilesmariani commented on src/redux/positions/thunks.js
> +      password: data.password
I don't think this is working, let's start checking things before committing

2021-12-17 04:13 UTC, aquilesmariani commented on src/redux/positions/thunks.js
> +      }
remove all console.logs

2021-12-17 04:13 UTC, aquilesmariani commented on src/redux/positions/reducer.js
> +        list: [...state.list]
We aren't updating the list here, it's just a copy of the previous one

2021-12-17 04:13 UTC, aquilesmariani commented on src/Components/Positions/index.js
> +  const OnClickdeletePosition = () => {
```suggestion
  const onClickdeletePosition = () => {
```

2021-12-17 04:13 UTC, aquilesmariani commented on src/Components/Positions/Form/index.js
>    const [companyName, setCompanyName] = useState('');
Why do we have company name and company id? Do we need both? If so, shouldn't them be related (maybe autocomplete the `company name` field if an id has been found)?

2021-12-19 19:20 UTC, ManuelLopezAnido commented on src/redux/positions/reducer.js
> +        list: [...state.list]
It isn't important cause just after updataing or adding the page will go to `/positions` and the store `list` will automatcally recharged

2021-12-19 19:54 UTC, ManuelLopezAnido commented on src/Components/Positions/Form/index.js
>    const [companyName, setCompanyName] = useState('');
I am not sure how to acomplish it in that way, should I make a new call with the Id to do it?

2021-12-19 22:31 UTC, leimeterjoaquin approved these changes

2021-12-19 23:18 UTC, aquilesmariani approved these changes
Looks good!

2021-12-19 23:18 UTC, merged