BaSD/MS-46/Postulants: added the logic of redux
BaSD-2021/Aquiles-MindSet-app pull request #22
Opened 2021-12-14 02:17 UTC by MicaQuarleri

2021-12-17 03:03 UTC, aquilesmariani commented
@MicaQuarleri  Let's pause this one until we merge https://github.com/BaSD-2021/Aquiles-MindSet-app/pull/20 since it has a lot of changes that were made on that branch

2021-12-18 01:48 UTC, aquilesmariani commented
@MicaQuarleri since you merged [your previous PR](https://github.com/BaSD-2021/Aquiles-MindSet-app/pull/20), you have conflicts to solve. Please merge development to this branch and then we can review this one.

2021-12-18 14:17 UTC, ignacioaristo requested changes

2021-12-18 14:17 UTC, ignacioaristo commented on src/Components/Councelors/index.js
> +
Remove the `console.log`

2021-12-18 14:17 UTC, ignacioaristo commented on src/redux/postulants/constants.js
> +export const GET_ONE_POSTULANT_FULFILLED = 'GET_ONE_POSTULANT_FULFILLED';
Maybe remove this comments at the end of the line.

2021-12-18 21:17 UTC, ignacioaristo approved these changes

2021-12-19 15:03 UTC, aquilesmariani approved these changes
Looks nice @MicaQuarleri!

2021-12-19 15:10 UTC, merged