BaSD-MS-50-Sessions: Redux
BaSD-2021/Aquiles-MindSet-app pull request #23
Opened 2021-12-14 14:26 UTC by ignacioaristo

Added the logic of Redux and Redux thunk to handle Sessions

2021-12-17 03:28 UTC, aquilesmariani requested changes

2021-12-17 03:28 UTC, aquilesmariani commented on src/redux/sessions/thunks.js
> +  console.log(data, 'data');
remove console.logs

2021-12-17 03:28 UTC, aquilesmariani commented on src/redux/sessions/thunks.js
> +  fetch(`${URL}/sessions/`)
```suggestion
  fetch(`${URL}/sessions`)
```

2021-12-17 03:28 UTC, aquilesmariani commented on src/Components/Sessions/index.js
> +              <td>{session.postulantId}</td>
`postulantId` seems to be an object and you can't place it this way, did you forget to commit something to the server or just need to show in here the actual data?

2021-12-17 17:05 UTC, ignacioaristo commented on src/redux/sessions/thunks.js
> +  fetch(`${URL}/sessions/`)
Changed it

2021-12-17 17:06 UTC, ignacioaristo commented on src/redux/sessions/thunks.js
> +  console.log(data, 'data');
Removed it.

2021-12-17 17:53 UTC, ignacioaristo commented on src/Components/Sessions/index.js
> +              <td>{session.postulantId}</td>
Fixed it, i need to show the data inside, example, `postulantId.firstName`

2021-12-18 13:22 UTC, aquilesmariani approved these changes
🚀

2021-12-18 14:37 UTC, leimeterjoaquin approved these changes

2021-12-18 14:45 UTC, merged