BaSD/MS-58/Positions
BaSD-2021/Aquiles-MindSet-app pull request #34
Opened 2021-12-21 00:00 UTC by MicaQuarleri

The controller file was change in order to send an object and not onlya msg

2021-12-28 00:38 UTC, ignacioaristo requested changes
I couldn't find the error, but if you Create a new `positions `the app crash. When you Update a `position `the app works perfectly

2021-12-28 00:38 UTC, ignacioaristo commented on src/Components/Admin/Positions/Form/index.js
> +  console.log(selectedPosition);
Remove this `console.log`

2021-12-28 21:24 UTC, leimeterjoaquin approved these changes
Nice, remove console log before merging!

2021-12-29 11:20 UTC, ignacioaristo approved these changes
Perfect

2021-12-29 11:25 UTC, merged