BaSD-MS-55: Final form clients
BaSD-2021/Aquiles-MindSet-app pull request #35
Opened 2021-12-21 00:25 UTC by MicaQuarleri

2021-12-28 00:43 UTC, ignacioaristo requested changes

2021-12-28 00:43 UTC, ignacioaristo commented on src/Components/Admin/Clients/Form/index.js
> +      console.log(formValues);
Remove this `console.log`

2021-12-28 00:43 UTC, ignacioaristo commented on src/Components/Admin/Clients/Form/index.js
> +      console.log(formValues);
Remove this `console.log`

2021-12-28 23:47 UTC, ignacioaristo approved these changes

2021-12-29 19:12 UTC, ManuelLopezAnido commented on src/Components/Admin/Clients/Form/index.js
> +      dispatch(selectedToDefault());
Is this action necessary?

2021-12-29 19:12 UTC, ManuelLopezAnido commented on src/Components/Admin/Clients/Button/index.js
> +function Button(props) {
Why there is Button Component and not shared one ?

2021-12-30 11:43 UTC, MicaQuarleri commented on src/Components/Admin/Clients/Button/index.js
> +function Button(props) {
Yes, when we were doing the final form we realized that this button was missing. I added it for the entity but later I will make a ticket to add it in shared

2021-12-30 19:35 UTC, leimeterjoaquin requested changes
Please pull development. There are no interviews or job offers on the postulant's part of the app.

2021-12-30 19:35 UTC, leimeterjoaquin commented on src/Components/Admin/Clients/Form/index.js
>  import Input from 'Components/Shared/Input';
Here we are using 
`import Input from 'Components/Shared/FormInput';`
also pull development to get the sahred `FormInput`

2021-12-30 19:35 UTC, leimeterjoaquin commented on src/Components/Admin/Clients/Form/index.js
> +      dispatch(selectedToDefault());
The same as when we use `cleanError` or `errorToDefault`. It's safe and used so that the state is exactly the way we want it to be. Maybe it can be changed but for now it's useful and we used it on every form.

2021-12-31 01:41 UTC, ManuelLopezAnido commented on src/Components/Admin/Clients/Form/index.js
> +      dispatch(selectedToDefault());
Okeyy seems good

2021-12-31 01:41 UTC, ManuelLopezAnido commented on src/Components/Admin/Clients/Button/index.js
> +function Button(props) {
Okiss thanks

2022-01-03 12:00 UTC, leimeterjoaquin approved these changes

2022-01-03 13:06 UTC, merged