BaSD-MS-56: Final form counselors
BaSD-2021/Aquiles-MindSet-app pull request #36
Opened 2021-12-21 00:34 UTC by MicaQuarleri

2021-12-22 19:43 UTC, aquilesmariani requested changes
Almost done!

I'm facing this when I get into the counselor form, we should fix it
<img width="802" alt="Screen Shot 2021-12-22 at 16 41 24" src="https://user-images.githubusercontent.com/8579539/147146802-edc2aeaa-dfa0-459b-8275-1805236b69ec.png">

2021-12-28 00:46 UTC, ignacioaristo approved these changes
Looks good to me

2021-12-29 15:50 UTC, aquilesmariani requested changes
Check that you didn't resolve conflicts in your last merge

2021-12-29 15:50 UTC, aquilesmariani commented on package-lock.json
> +>>>>>>> 76483c2333de1647a53b3655fba1d287edb70e68
You need to fix this instead of committing the conflicts

2021-12-29 15:50 UTC, aquilesmariani commented on package-lock.json
> +>>>>>>> 76483c2333de1647a53b3655fba1d287edb70e68
This one too

2022-01-03 12:17 UTC, leimeterjoaquin requested changes

2022-01-03 12:24 UTC, leimeterjoaquin commented on src/Components/Shared/Input/index.js
>  import styles from './input.module.css';
profiles form doesn't work, for example

2022-01-03 13:36 UTC, aquilesmariani approved these changes
Looks great!

2022-01-03 13:57 UTC, merged