Feature ms 69 create specifics secreenflows for postulants
BaSD-2021/Aquiles-MindSet-app pull request #38
Opened 2021-12-21 02:40 UTC by ManuelLopezAnido

Components Interview and JobOffers done. 
Making Redux and backend for Interview

2021-12-24 20:06 UTC, ignacioaristo requested changes

2021-12-24 20:06 UTC, ignacioaristo commented on src/Components/Postulant/Home/index.js
> +      <div className={styles.informationField}>
Remove this `console.log`

2021-12-24 20:06 UTC, ignacioaristo commented on src/Components/Postulant/Interviews/index.js
> +  console.log(interviews);
This too.

2021-12-24 20:06 UTC, ignacioaristo commented on src/Components/Postulant/Interviews/index.js
> +  const OnClickDelete = (id) => {
This too.

2021-12-24 20:06 UTC, ignacioaristo commented on src/Components/Postulant/JobOffers/index.js
> +
This too.

2021-12-30 00:39 UTC, ManuelLopezAnido commented on src/Components/Postulant/Home/index.js
> +      <div className={styles.informationField}>
Done

2021-12-30 00:39 UTC, ManuelLopezAnido commented on src/Components/Postulant/Interviews/index.js
> +  console.log(interviews);
Done too

2021-12-30 00:40 UTC, ManuelLopezAnido commented on src/Components/Postulant/Interviews/index.js
> +  const OnClickDelete = (id) => {
All done

2021-12-30 00:40 UTC, ManuelLopezAnido commented on src/Components/Postulant/JobOffers/index.js
> +
All right

2021-12-30 18:22 UTC, ignacioaristo approved these changes
Nice

2022-01-03 12:23 UTC, leimeterjoaquin approved these changes

2022-01-03 13:25 UTC, merged