BaSD-MS-21: Postulants create react logic
BaSD-2021/Aquiles-MindSet-app pull request #4
Opened 2021-11-30 02:00 UTC by leimeterjoaquin

# React postulants app

## Added:
-list postulants
-delete postulants
-edit postulant
-create postulant

## notes
Availability logic missing.

2021-12-02 04:22 UTC, aquilesmariani reviewed
Didn't finish reviewing. 

You can start merging your server [changes](https://github.com/BaSD-2021/Aquiles-MindSet-server/pull/30) and fixing what I've commented in here.

2021-12-02 04:22 UTC, aquilesmariani commented on .eslintrc.json
> +    }
Be careful, this indentation was fine because it needs to be nested.

2021-12-02 04:22 UTC, aquilesmariani commented on .eslintrc.json
>      },
Same as above

2021-12-02 04:22 UTC, aquilesmariani commented on src/Components/Postulants/Input/input.module.css
> +}
Let's get rid of empty selectors

2021-12-02 04:22 UTC, aquilesmariani commented on src/Components/Postulants/Input/input.module.css
> +  background-color: rgb(212, 212, 212);
We should start getting used to put colors in hex format instead of rgb

2021-12-02 04:22 UTC, aquilesmariani commented on src/Components/Postulants/Input/input.module.css
> +  min-width: 50ch;
Any reason you're using `ch` instead of `rem`?

2021-12-02 04:22 UTC, aquilesmariani commented on src/Components/Postulants/Modal/index.jsx
> +  };
```suggestion
  const deletePostulant = () => {
    props.actionPostulant(idToUse);
    props.closeModal();
  };
```

2021-12-02 04:22 UTC, aquilesmariani commented on src/Components/Postulants/Modal/index.jsx
> +          <button onClick={() => onClick(props.idToUse)}>{props.buttonText}</button>
```suggestion
          <button onClick={deletePostulant}>{props.buttonText}</button>
```

2021-12-02 04:22 UTC, aquilesmariani commented on src/Components/Postulants/Modal/index.jsx
> +      <div className={styles.modal}>
What's the difference of using 2 divs instead of just one if you aren't separating content?

2021-12-02 04:22 UTC, aquilesmariani commented on src/Components/Postulants/PostulantsForm/index.jsx
> +  const [HighSchoolGraduateYearValue, setHighSchoolGraduateYearValue] = useState(0);
```suggestion
  const [highSchoolGraduateYearValue, setHighSchoolGraduateYearValue] = useState(0);
```

2021-12-02 22:09 UTC, leimeterjoaquin commented on src/Components/Postulants/Input/input.module.css
> +  min-width: 50ch;
I use ch when Im thinking horizontally. So the input is 50 characters wide. when thinking vertically I do use rem o em.

2021-12-02 22:15 UTC, leimeterjoaquin commented on src/Components/Postulants/Modal/index.jsx
> +      <div className={styles.modal}>
countainer is the grey area of the modal.

2021-12-03 00:34 UTC, aquilesmariani commented on src/Components/Postulants/Modal/index.jsx
> +      <div className={styles.modal}>
can't you fix it by working with the CSS `box-model` idea? Separating with margin and padding?

2021-12-03 00:38 UTC, aquilesmariani requested changes
Still can't test the app because it's failing on heroku.

2021-12-03 00:38 UTC, aquilesmariani commented on src/Components/Postulants/index.js
> +    const url = `${process.env.REACT_APP_API}/api/postulants/delete/${id}`;
If you check on the deployed app in [heroku](https://basd-2021-aq-feature-ms-spwdmd.herokuapp.com/postulants) , the requests to the server are failing cause `/api` is duplicated. It is probably that `/api` already included in the 
`REACT_APP_API` environment variable. You should remove it from here and add it in your `.env` file


![image](https://user-images.githubusercontent.com/8579539/144524841-2ee4a32d-bc95-442e-b5a6-e38df8490594.png)

```suggestion
    const url = `${process.env.REACT_APP_API}/postulants/delete/${id}`;
```

2021-12-03 17:37 UTC, leimeterjoaquin commented on src/Components/Postulants/index.js
> +    const url = `${process.env.REACT_APP_API}/api/postulants/delete/${id}`;
Thanks for letting me know where the issue was.

2021-12-03 19:33 UTC, ignacioaristo requested changes

2021-12-03 19:33 UTC, ignacioaristo commented on src/Components/Postulants/index.js
> +      .catch((error) => console.log(error));
Maybe you should return the `error` on the UI

2021-12-03 19:33 UTC, ignacioaristo commented on src/Components/Postulants/index.js
> +    fetch(url, {
remove the `console.log`

2021-12-03 19:33 UTC, ignacioaristo commented on src/Components/Postulants/index.js
> +            console.log(message);
remove the `console.log`

2021-12-03 19:33 UTC, ignacioaristo commented on src/Components/Postulants/index.js
> +    event.stopPropagation();
remove the `console.log`

2021-12-03 19:45 UTC, leimeterjoaquin commented on src/Components/Postulants/index.js
> +      .catch((error) => console.log(error));
Shouldn't we do this on this weeks proyect, using the shared modal?

2021-12-04 12:23 UTC, merged