BaSD-MS-71: Redux postulants
BaSD-2021/Aquiles-MindSet-app pull request #40
Opened 2021-12-22 10:46 UTC by MicaQuarleri

I had to apply redux to the part where the postulants are listed. Control only this part, not the one to add as certain parts of the share Input component were changed with the final form logic, it is not working.

2021-12-29 11:22 UTC, ignacioaristo approved these changes
Nice

2021-12-29 11:27 UTC, ignacioaristo approved these changes

2021-12-30 19:17 UTC, leimeterjoaquin requested changes
Please pull development. You can see on the deploy that there is no postulant flow or list styles.

2022-01-03 21:38 UTC, leimeterjoaquin approved these changes

2022-01-04 10:55 UTC, merged