BaSD-MS-68: Create home page screen
BaSD-2021/Aquiles-MindSet-app pull request #44
Opened 2022-01-05 01:22 UTC by ignacioaristo

General Home page was created.

2022-01-06 14:41 UTC, leimeterjoaquin requested changes
And I don't know why it's not deployed

2022-01-06 14:41 UTC, leimeterjoaquin commented on src/Components/Postulant/JobOffers/index.js
> +                // jobOffer.clientName.toLowerCase().includes(inputSearchBar.toLowerCase()) ||
You should uncomment, this is fixed now. It was a DB error. Or you could add 
`jobOffer.clientName?.toLowerCase().includes(inputSearchBar.toLowerCase()) ||`
I think it might get fixed with the question mark.

2022-01-07 23:38 UTC, ignacioaristo commented on src/Components/Postulant/JobOffers/index.js
> +                // jobOffer.clientName.toLowerCase().includes(inputSearchBar.toLowerCase()) ||
Fixed it!

2022-01-08 23:13 UTC, leimeterjoaquin approved these changes

2022-01-11 01:10 UTC, MicaQuarleri approved these changes

2022-01-11 01:10 UTC, merged