Ms 18 applications
BaSD-2021/Aquiles-MindSet-app pull request #5
Opened 2021-11-30 02:45 UTC by ManuelLopezAnido

Applications done

2021-12-02 16:37 UTC, aquilesmariani requested changes

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/index.js
> +      .catch((error) => error);
We should show this since the user won't realize there are issues

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Modal/modalApplications.module.css
> +  background-color: rgba(0,0,0,0,5);
Let´s keep consistency across the styling files using hex values for colors

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Form/FormApplication.js
> +  const AppId = params.get('id');
```suggestion
  const appId = params.get('id');
```

2021-12-02 16:37 UTC, aquilesmariani commented on .eslintrc.json
> +    "react/prop-types": 0
I think you should rollback changes on this file

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Form/FormApplication.js
> +      response.json();
Is this needed here? I think you can just redirect on this line and remove the 2nd `.then`
```suggestion
      window.location.href = `/applications`;
```

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Form/FormApplication.js
> +    console.log(options);
```suggestion
```

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Form/FormApplication.js
> +    })
```suggestion
```

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Form/FormApplication.js
> +      return error;
Let's display the error message somewhere in the UI (inside the modal is a good option)

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Form/FormApplication.js
> +  console.log (position, company,postulant, applicationState );
```suggestion
```

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/Form/FormApplication.js
> +      url = `${process.env.REACT_APP_API}/api/applications/add`;
If you check on the deployed app in [heroku](https://basd-2021-aq-ms-18-appl-fikann.herokuapp.com/applications) , the requests to the server are failing cause `/api` is duplicated. It is probably that `/api` already included in the 
`REACT_APP_API` environment variable. You should remove it from here and add it in your `.env` file

![image](https://user-images.githubusercontent.com/8579539/144464025-a62bdb30-81bc-4f9a-80b9-6d51f7836060.png)


```suggestion
      fetch(`${process.env.REACT_APP_API}/clients/id/${clientId}`)
```

2021-12-02 16:37 UTC, aquilesmariani commented on src/Components/Applications/index.js
> +  console.log("datass: ", applications);
No console.log allowed

2021-12-04 15:19 UTC, ignacioaristo approved these changes
Looks good to me

2021-12-04 16:15 UTC, leimeterjoaquin approved these changes

2021-12-04 17:25 UTC, merged