MS-24-Positions: positions features done
BaSD-2021/Aquiles-MindSet-app pull request #6
Opened 2021-11-30 02:46 UTC by ManuelLopezAnido

Positions done

2021-12-02 16:46 UTC, aquilesmariani requested changes
Please review comments I've also left [here](https://github.com/BaSD-2021/Aquiles-MindSet-app/pull/5#pullrequestreview-821036810) because most of them are repeated.

2021-12-02 16:46 UTC, aquilesmariani commented on src/Components/Positions/positions.module.css
> +  flex-direction:column;
```suggestion
  flex-direction: column;
```

2021-12-02 16:46 UTC, aquilesmariani commented on src/Components/Positions/Form/FormPositions.js
> +    console.log("El curepo es: ", options);
```suggestion
```

2021-12-02 16:46 UTC, aquilesmariani commented on src/Components/Positions/Form/FormPositions.js
> +      url = `${process.env.REACT_APP_API}/api/positions/create`;
If you check on the deployed app in [heroku](https://basd-2021-aq-ms-24-posi-owlhvx.herokuapp.com/positions) , the requests to the server are failing cause `/api` is duplicated. It is probably that `/api` already included in the 
`REACT_APP_API` environment variable. You should remove it from here and add it in your `.env` file

```suggestion
      url = `${process.env.REACT_APP_API}/positions/create`;
```

2021-12-02 16:46 UTC, aquilesmariani commented on .eslintrc.json
> +  "extends": ["eslint:recommended", "plugin:react/recommended" /*, "plugin:prettier/recommended"*/],
Let's roll back these file changes

2021-12-04 14:02 UTC, ignacioaristo requested changes

2021-12-04 14:02 UTC, ignacioaristo commented on src/Components/Positions/index.js
> +
Remove those console.log

2021-12-04 14:51 UTC, ignacioaristo requested changes

2021-12-04 14:51 UTC, ignacioaristo commented on src/Components/Positions/index.js
> +    fetch(`${process.env.REACT_APP_API}/api/positions`)
Maybe you need to remove this `/api`

2021-12-04 14:51 UTC, ignacioaristo commented on src/Components/Positions/index.js
> +    const url = `${process.env.REACT_APP_API}/api/positions/delete/${idPos}`;
This one too.

2021-12-04 16:25 UTC, leimeterjoaquin commented on src/Components/Positions/Form/FormPositions.js
> +        });
add a catch.
maybe
```
.catch((error) => {
  return error;
});
```
This should be a modal, we can implement it for this week

2021-12-04 17:25 UTC, merged