BaSD-MS-22-Sessions:  Create React Logic
BaSD-2021/Aquiles-MindSet-app pull request #7
Opened 2021-12-01 21:00 UTC by ignacioaristo

Resume:
Frontend was connected with backend using React.

Methods developed for Sessions:

Get all the Sessions

Create a Session

Click on Add Session button to display the form.

Update a Sessions
Click on the row of the Session to display the form and rewrite it.

Delete a Session
Click on the trash can icon to delete the Session.

Modal was created for delete option.

Validations were added to every form.

2021-12-02 16:56 UTC, aquilesmariani requested changes
Please check on the comments on the [clients' PR](https://github.com/BaSD-2021/Aquiles-MindSet-app/pull/1#pullrequestreview-820985070) and apply them here as well since most are repeated.

2021-12-02 16:56 UTC, aquilesmariani commented on .eslintrc.json
> +      "react/prop-types": 0
Let's get rid of these changes

2021-12-03 00:29 UTC, ignacioaristo commented on .eslintrc.json
> +      "react/prop-types": 0
Chages removed

2021-12-03 01:08 UTC, aquilesmariani approved these changes
LGTM!

2021-12-03 01:52 UTC, merged